# docker-compose.yaml

services:
  vpp:
    build:
      context: ./vpp-container
    container_name: vpp-container
    privileged: true
    # Mount the custom startup.conf into the container
    volumes:
      - ./vpp-container/startup.conf:/etc/vpp/startup.conf:ro
    networks:
      link1_net:
        ipv4_address: 192.168.10.2
      link2_net:
        ipv4_address: 192.168.20.2
      link3_net:
        ipv4_address: 192.168.30.2
      link4_net:
        ipv4_address: 192.168.40.2
      link5_net:
        ipv4_address: 192.168.50.2

  ubuntu:
    build:
      context: ./ubuntu-container
    container_name: ubuntu-container
    privileged: true
    command: tail -f /dev/null
    networks:
      link1_net:
        ipv4_address: 192.168.10.3
      link2_net:
        ipv4_address: 192.168.20.3
      link3_net:
        ipv4_address: 192.168.30.3
      link4_net:
        ipv4_address: 192.168.40.3
      link5_net:
        ipv4_address: 192.168.50.3

# Define all 5 bridge networks with their subnets
networks:
  link1_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
  link2_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24
  link3_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.30.0/24
  link4_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.40.0/24
  link5_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.50.0/24